export const AUTH_USER = 'AUTH_USER',
             UNAUTH_USER = 'UNAUTH_USER',
             AUTH_ERROR = 'AUTH_ERROR',
             FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST',
             RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST',
             FETCH_USER_PROFILE = 'FETCH_USER_PROFILE',
             PROTECTED_TEST = 'PROTECTED_TEST'